# Configuration file for Softmax Regression project

# Model configuration
model:
  input_size: 784
  num_classes: 10

# Training configuration
training:
  epochs: 30
  batch_size: 128
  learning_rate: 0.01
  optimizer: "sgd" # sgd, adam, rmsprop
  loss: "categorical_crossentropy"
  metrics: ["accuracy"]

  # Validation
  validation_split: 0.0 # Use separate test set as validation

  # Early stopping
  early_stopping:
    enabled: true
    patience: 5
    monitor: "val_loss"
    min_delta: 0.001
    restore_best_weights: true

  # Model checkpoint
  model_checkpoint:
    enabled: true
    filepath: "results/models/best_model.h5"
    monitor: "val_accuracy"
    save_best_only: true

  # Learning rate reduction
  reduce_lr:
    enabled: true
    monitor: "val_loss"
    factor: 0.5
    patience: 3
    min_lr: 1.0e-7

# Custom training configuration
custom_training:
  enabled: false
  optimizer: "sgd"
  learning_rate: 0.001
  loss: "categorical_crossentropy"

# Data configuration
data:
  dataset: "mnist"
  normalize: true
  flatten: true
  subset_size: null # Use full dataset, or specify number for subset
  shuffle_buffer_size: 10000

# Evaluation configuration
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"

  # Confusion matrix
  confusion_matrix:
    enabled: true
    normalize: true

  # Classification report
  classification_report:
    enabled: true

# Visualization configuration
visualization:
  training_history:
    enabled: true
    save_path: "results/plots/training_history.png"
    figsize: [12, 4]

  sample_predictions:
    enabled: true
    num_samples: 16
    save_path: "results/plots/sample_predictions.png"
    figsize: [12, 8]

  confusion_matrix:
    enabled: true
    save_path: "results/plots/confusion_matrix.png"
    figsize: [8, 6]

# Logging configuration
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "results/logs/training.log"

# Paths configuration
paths:
  models: "results/models"
  plots: "results/plots"
  logs: "results/logs"
  data: "data"

# Random seed for reproducibility
random_seed: 42

# GPU configuration
gpu:
  enabled: true
  memory_growth: true # Allow memory growth instead of allocating all GPU memory
